name: Build Spring Boot style docs

on:
  workflow_dispatch:

jobs:
    build:
        name: "Test with ${{ matrix.version }}"
        strategy:
            matrix:
                version: [ 8.0.275.hs-adpt ]
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - name: Cache local Maven repository
              uses: actions/cache@v2
              with:
                  path: ~/.m2/repository
                  key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
                  restore-keys: ${{ runner.os }}-maven-
            - name: Download ${{ matrix.version }}
              uses: sdkman/sdkman-action@master
              id: sdkman
              with:
                  candidate: java
                  version: ${{ matrix.version }}
            - name: Set up ${{ matrix.version }}
              uses: actions/setup-java@v1
              with:
                  java-version: 11
                  jdkFile: ${{ steps.sdkman.outputs.file }}
            - name: Build docs
              run: |
                   gradle asciidoctor
            - name: Upload docs
              uses: JamesIves/github-pages-deploy-action@releases/v3
              with:
                  github-token: ${{ secrets.ACCESS_TOKEN }}
                  branch: gh-pages
                  folder: build/docs
