# This is a basic workflow to help you get started with Actions

name: Link Checker

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ gh-pages ]
  schedule:
    - cron: "0 2 * * 1-5"
  workflow_dispatch:

# jobs:
#   link-check:
#     runs-on: ubuntu-latest
#     steps:
#     - name: Broken Link Check
#       uses: technote-space/broken-link-checker-action@v1.1.3
#       with:
#         TARGET: https://hui1110.github.io/spring-cloud-azure/current/reference/html/index.html
#         EXCLUDED_KEYWORDS: localhost,host_name
#         EXCLUDE_LINKS_TO_SAME_PAGE: false



# jobs:
#   broken_link_checker_job:
#     runs-on: ubuntu-latest
#     name: Check for broken links
#     steps:
#     - name: Check for broken links
#       id: link-report
#       uses: celinekurpershoek/link-checker@v1.0.1
#       with:
#         # Required:
#         url: 'https://hui1110.github.io/spring-cloud-azure/current/reference/html/index.html'
#         excludedKeywords: 'localhost,host_name'
#         # optional:
#         honorRobotExclusions: false
#         ignorePatterns: 'github,google'
#     - name: Get the result
#       run: echo "${{steps.link-report.outputs.result}}"

# jobs:
#   markdown-link-check:
#     runs-on: ubuntu-latest
#     steps:
#     - uses: actions/checkout@master
#     - uses: gaurav-nelson/github-action-markdown-link-check@v1
#       with:
#         use-quiet-mode: 'yes'
#         folder-path: 'docs/src/main/asciidoc'
#         file-path: './README.md, ./LICENSE, ./md/file4.markdown'


jobs:
  check_html_links_job:
    runs-on: ubuntu-latest
    name: A job to test check-html-links-action
    steps:  
      - uses: actions/checkout@v2
      - name: Cache local Maven repository
        uses: actions/cache@v2
        with:
            path: ~/.m2/repository
            key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
            restore-keys: ${{ runner.os }}-maven-
      - name: Download ${{ matrix.version }}
        uses: sdkman/sdkman-action@master
        id: sdkman
        with:
            candidate: java
            version: ${{ matrix.version }}
      - name: Set up ${{ matrix.version }}
        uses: actions/setup-java@v1
        with:
            java-version: 11
            jdkFile: ${{ steps.sdkman.outputs.file }}
      - name: Build docs
        run: |
            pwd
            dir
            cd docs
            pwd
            mvn clean install -Pdocs
      - name: check-html-links-action step
        id: check-links
        uses: modernweb-dev/check-html-links-action@v1
        with:
          doc-folder: docs/target/generated-docs
          excludedKeywords: localhost,host_name
