# This is a basic workflow to help you get started with Actions

name: Link Checker

# Controls when the workflow will run
on:
  schedule:
    - cron: "0 2 * * 1-5"
  workflow_dispatch:

jobs:
  check_html_links_job:
    runs-on: ubuntu-latest
    name: check-html-links-action
    steps:  
      - uses: actions/checkout@v2
      - name: Link Checker
        uses: peter-evans/link-checker@v1
        with:
          args: -d --document-root ./4.0.0/reference/html -r -x "localhost|127.0.0.1" 
      - name: check result
      - run: | 
          errors = cat link-checker/out.md | grep 'ERROR' | wc -l 
     #    run: exit 1
      
      
