# This is a basic workflow to help you get started with Actions

name: Broken Link Checker

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  check_html_links_job:
    runs-on: ubuntu-latest
    name: Check-Links-Action
    steps:
      - uses: snow-actions/sparse-checkout@v1.1.0
        name: Checkout Azure/azure-sdk-for-java
        with:
          patterns: |
           sdk/spring
           eng
           sdk/keyvault
           sdk/boms
           sdk/aot
          repository: Azure/azure-sdk-for-java
          ref: main
          path: azure-sdk-for-java
            
      - name: Build files needed for runtime     
        run: |
          ls -al
          cd azure-sdk-for-java
          ls -al
          mvn clean install -Dmaven.javadoc.skip=true -DskipTests \
            -Dcheckstyle.skip=true \
            -ntp \
            -Dspotbugs.skip=true \
            -Drevapi.skip=true -Djacoco.skip=true \
            -Dparallel-test-playback \
            -Pdev \
            -f sdk/spring/pom.xml

      - uses: actions/checkout@v2

      - name: Build Docs
        run: |
          ./mvnw clean install -P docs -pl docs -DskipTests

      - name: Html Link Checker
        id: html-link-report
        uses: peter-evans/link-checker@v1
        with:
          args: -d --document-root ./docs/target/generated-docs -v -r -x "my|localhost|127.0.0.1"

      - name: Link version replacement
        run: |
          if [ -d "link-checker/" ] ; then
             cd link-checker
             sudo sed -i 's/spring-cloud-azure_*.*.*-beta.[0-9]/main/g' *
             sudo sed -i 's/```/ /g' *
             sudo mv out.md ../
          fi
      
      - uses: actions/checkout@master
    
      - uses: gaurav-nelson/github-action-markdown-link-check@1.0.13
        name: Markdown Links Check
        with:
           use-quiet-mode: 'yes'
           use-verbose-mode: 'yes'
           config-file: '.github/workflows/mlc_config.json'
      
#       - name: Markdown Links Check
#         id: markdown-link-report
#         uses: peter-evans/link-checker@v1
#         with:
#           args: -d . -v -r -x "my|localhost|127.0.0.1" *.md

#       - name: Fail if there were link errors
#         run: exit ${{ steps.markdown-link-report.outputs.exit_code }}
