# This is a basic workflow to help you get started with Actions

name: Init Azure

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  check_html_links_job:
    runs-on: ubuntu-latest
    name: Check-Links-Action
    steps:
      - run: |
          git init azure-sdk-for-java
          cd azure-sdk-for-java
          git remote add origin https://github.com/Azure/azure-sdk-for-java.git
          git config core.sparsecheckout true
          echo "sdk/spring" >> .git/info/sparse-checkout
          echo "eng" >> .git/info/sparse-checkout
          echo "sdk/keyvault" >> .git/info/sparse-checkout
          echo "sdk/boms" >> .git/info/sparse-checkout
          echo "sdk/aot" >> .git/info/sparse-checkout
          git pull --depth=1 origin main
          mvn clean install -Dmaven.javadoc.skip=true -DskipTests \
            -Dcheckstyle.skip=true \
            -ntp \
            -Dspotbugs.skip=true \
            -Drevapi.skip=true -Djacoco.skip=true \
            -Dparallel-test-playback \
            -Pdev \
            -f sdk/spring/pom.xml
