# This is a basic workflow to help you get started with Actions

name: Link Checker

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ gh-pages ]
  schedule:
  - cron: "0 2 * * 1-5"
  workflow_dispatch:

jobs:
  link-check:
    runs-on: ubuntu-latest
    steps:
    - uses: technote-space/broken-link-checker-action@v1.1.3
      with:
        TARGET: https://microsoft.github.io/spring-cloud-azure/current/reference/html/index.html


