# This is a basic workflow to help you get started with Actions

name: Schedule Current Link Check

# Controls when the workflow will run
on:
  # The schedule event allows you to trigger a workflow at a scheduled time.
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * *'

jobs:
  broken_link_checker_job:
    runs-on: ubuntu-latest
    name: Check for broken links
    steps:
#     - name: Check for broken links
#       id: link-report
#       uses: celinekurpershoek/link-checker@v1.0.1
#       with:
#         # Required:
#         url: 'https://microsoft.github.io/spring-cloud-azure/current/reference/html/index.html'
#         # optional:
#         honorRobotExclusions: false
#         ignorePatterns: 'localhost,127.0.0.1,my'
#         recursiveLinks: false 
     - name: Check for broken links
       id: link-report
       uses: ruzickap/action-my-broken-link-checker@v2
       with:
         url: https://microsoft.github.io/spring-cloud-azure/
         cmd_params: '"--one-page-only --verbose --color=always --exclude="(my|localhost|127.0.0.1)"'
        
     - name: Get the result
       run: echo "${{steps.link-report.outputs.result}}"
